### ISSUE TITLE
Missing 2 Include files

### ISSUE THREAD

**Issue by Sony-1972** [xcatp/ahk-meow-paste#1]
Hi
Where to get below 2 files ?

#Include g:\AHK\git-ahk-lib\util\log\log.ahk
#Include g:\AHK\git-ahk-lib\util\config\MeowConfEx.ahk

**Comment by xcatp** [comment]
Hi
I haven't push it to Github yet, but you can click there [Gitee Ahk-lib](https://gitee.com/dkwd/ahk-lib), and clone it.
You can find the missing files here. 
I will upload the other ahk repository to Github later :D.

**Comment by xcatp** [comment]
The latest version of the code has added dependent external scripts to the **_lib** directory,
 so it can run without doing anything else.
Make sure that your code is up to date XD.
